version: '3'
services:
  mysql_db:
    image: mysql:8
    container_name: mysql_dbtest
    security_opt:
      - "seccomp:unconfined"
    ports:
      - "3200:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - mysql_db_data:/var/lib/mysql
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_dbtest
    ports:
      - 5400:5432
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=microservice

  hotel-management-service-registry-main:
    build: ./hotel-management-service-registry-main
    image: test_hotel-management-service-registry-main
    container_name: hotel-management-service-registry-main1
    volumes:
      - app_data:/app/Server/Microservices
    environment:
      EUREKA_INSTANCE_HOSTNAME: hotel-management-service-registry-main
    ports:
      - 8761:8761
  
  hotel-management-config-server-main:
    build: ./hotel-management-config-server-main
    image: test_hotel-management-config-server-main
    container_name: hotel-management-config-server-main1
    volumes:
      - app_data:/app/Server/Microservices
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://hotel-management-service-registry-main:8761/eureka
    ports:
      - 8085:8085

  hotel-management-user-service-main:
    build: ./hotel-management-user-service-main
    image: test_hotel-management-user-service-main
    container_name: hotel-management-user-service-main1
    volumes:
      - app_data:/app/Server/Microservices
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/microservices?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://hotel-management-service-registry-main:8761/eureka
      SPRING_CONFIG_IMPORT: optional:configserver:http://hotel-management-config-server-main:8085
    ports:
      - 8081:8081
    links:
      - mysql_db

  hotel-management-hotel-service-main:
    build: ./hotel-management-hotel-service-main
    image: test_hotel-management-hotel-service-main
    container_name: hotel-management-hotel-service-main1
    volumes:
      - app_data:/app/Server/Microservices
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/microservice
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://hotel-management-service-registry-main:8761/eureka
      SPRING_CONFIG_IMPORT: optional:configserver:http://hotel-management-config-server-main:8085
    ports:
      - 8082:8082
    links:
      - postgres_db

volumes:
  mysql_db_data:
  app_data:
  postgres_db_data: