version: '3'
services:
  mysql_db:
    image: mysql:8
    container_name: mysql_dbtest
    security_opt:
      - "seccomp:unconfined"
    ports:
      - "3200:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - mysql_db_data:/var/lib/mysql
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_dbtest
    ports:
      - 5400:5432
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=microservice

  hotel-management-service-registry-main:
    build: ./hotel-management-service-registry-main
    image: test_hotel-management-service-registry-main
    container_name: hotel-management-service-registry-main1
    volumes:
      - app_data:/app/Server/Microservices
    environment:
      EUREKA_INSTANCE_HOSTNAME: hotel-management-service-registry-main
    ports:
      - 8761:8761
  
  hotel-management-config-server-main:
    build: ./hotel-management-config-server-main
    image: test_hotel-management-config-server-main
    container_name: hotel-management-config-server-main1
    volumes:
      - app_data:/app/Server/Microservices
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://hotel-management-service-registry-main:8761/eureka
    ports:
      - 8085:8085

volumes:
  mysql_db_data:
  app_data:
  postgres_db_data: